var No1 = 11;
var No2 = 11;
var No3;
var No4;
console.log(No1);
console.log(No2);
console.log(No3);
console.log(No4);
console.log(typeof (No1));
console.log(typeof (No2));
console.log(typeof (No3));
console.log(typeof (No4));
